apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: image-import-event-listener
  name: image-import-listener
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-image-import-event-listener
